language: haskell-stack

env:
  - GHCVER=7.10.3 CABALVER=1.22
  - GHCVER=7.10.3 STACK_YAML=stack-lts5.yaml

matrix:
  fast_finish: true

meta:
  before_install:
    prefix:
      - ghdl --version
      - chmod +x install_iverilog.sh
      - ./install_iverilog.sh
      - export PATH=$PATH:$HOME/iverilog/bin
      - vvp -V
  script:
    suffix:
      - stack exec clash-testsuite

notifications:
  irc:
    channels:
    - "irc.freenode.org#clash-lang"
    skip_join: true
    template:
    - "\x0313clash-compiler\x0f/\x0306%{branch}\x0f \x0314%{commit}\x0f %{message} \x0302\x1f%{build_url}\x0f"
